# Generated by Django 5.2.10 on 2026-02-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_vendorportfolio_vendorportfolioimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorprofile",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="vendorProfileImages/"
            ),
        ),
        migrations.AlterField(
            model_name="vendorprofile",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="vendorprofile",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=10, null=True
            ),
        ),
    ]
