# Generated by Django 5.2.10 on 2026-02-21 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_vendorprofile_profile_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendorportfolio",
            name="vendor_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vendor_portfolios",
                to="profiles.vendorprofile",
            ),
        ),
    ]
