# Generated by Django 5.2.10 on 2026-02-21 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_alter_vendorportfolio_vendor_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendorportfolioimage",
            name="portfolio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="work_images",
                to="profiles.vendorportfolio",
            ),
        ),
    ]
