# Generated by Django 5.2.10 on 2026-02-27 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_service_service_icon_alter_address_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subservice",
            name="Service_image",
            field=models.ImageField(blank=True, null=True, upload_to="service_images/"),
        ),
        migrations.AlterField(
            model_name="subservice",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Services",
                to="services.service",
            ),
        ),
    ]
